task: ddong_direction
dataset_path: json
dataset_kwargs:
  data_files: ./data/direction/data.jsonl
output_type: generate_until

test_split: train

doc_to_visual: !function utils.ddong_doc_to_visaul
doc_to_text: !function utils.ddong_doc_to_text
doc_to_target: !function utils.ddong_doc_to_target
process_results: !function utils.ddong_process_results

generation_kwargs:
  max_new_tokens: 16
  temperature: 0
  top_p: 1.0
  do_sample: false

metric_list:
  - metric: exact_match
    aggregation: mean
    higher_is_better: true